// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227145310_UpdtFichaGerais")]
    partial class UpdtFichaGerais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("backend.Models.EquipamentoT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descr")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaT20Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Preco")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaT20Id");

                    b.ToTable("EquipamentoT20");
                });

            modelBuilder.Entity("backend.Models.FichaT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Atributos", "backend.Models.FichaT20.Atributos#AtributosEntity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Carisma")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Constituicao")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Destreza")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Forca")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Inteligencia")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Sabedoria")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Gerais", "backend.Models.FichaT20.Gerais#GeraisEntity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Classe")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Dinheiro")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Divindade")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Experiencia")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ImgUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Nivel")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Origem")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Raca")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Mana", "backend.Models.FichaT20.Mana#PontosEntity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Atual")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Maximo")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Temp")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Vida", "backend.Models.FichaT20.Vida#PontosEntity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Atual")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Maximo")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Temp")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.ToTable("FichaT20");
                });

            modelBuilder.Entity("backend.Models.HabilidadeT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.ToTable("HabilidadeT20");
                });

            modelBuilder.Entity("backend.Models.ModT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AplicaEm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EquipamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HabilidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("ModT20");
                });

            modelBuilder.Entity("backend.Models.PericiaT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaT20Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FichaT20Id");

                    b.ToTable("PericiaT20");
                });

            modelBuilder.Entity("backend.Models.EquipamentoT20", b =>
                {
                    b.HasOne("backend.Models.FichaT20", "FichaT20")
                        .WithMany("Equipamentos")
                        .HasForeignKey("FichaT20Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaT20");
                });

            modelBuilder.Entity("backend.Models.HabilidadeT20", b =>
                {
                    b.HasOne("backend.Models.FichaT20", "Ficha")
                        .WithMany("Habilidades")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("backend.Models.ModT20", b =>
                {
                    b.HasOne("backend.Models.EquipamentoT20", "Equipamento")
                        .WithMany("Mods")
                        .HasForeignKey("EquipamentoId");

                    b.HasOne("backend.Models.HabilidadeT20", "Habilidade")
                        .WithMany("Mods")
                        .HasForeignKey("HabilidadeId");

                    b.Navigation("Equipamento");

                    b.Navigation("Habilidade");
                });

            modelBuilder.Entity("backend.Models.PericiaT20", b =>
                {
                    b.HasOne("backend.Models.FichaT20", "FichaT20")
                        .WithMany("Pericias")
                        .HasForeignKey("FichaT20Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaT20");
                });

            modelBuilder.Entity("backend.Models.EquipamentoT20", b =>
                {
                    b.Navigation("Mods");
                });

            modelBuilder.Entity("backend.Models.FichaT20", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Habilidades");

                    b.Navigation("Pericias");
                });

            modelBuilder.Entity("backend.Models.HabilidadeT20", b =>
                {
                    b.Navigation("Mods");
                });
#pragma warning restore 612, 618
        }
    }
}
