// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219125947_Ini")]
    partial class Ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.EquipamentoT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FichaT20Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FichaT20Id");

                    b.ToTable("EquipamentoT20");
                });

            modelBuilder.Entity("backend.Models.FichaT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Constituicao")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Destreza")
                        .HasColumnType("int");

                    b.Property<int>("Dinheiro")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<int>("ManaAtual")
                        .HasColumnType("int");

                    b.Property<int>("ManaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("int");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FichaT20");
                });

            modelBuilder.Entity("backend.Models.HabilidadeT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.ToTable("HabilidadeT20");
                });

            modelBuilder.Entity("backend.Models.ModT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AplicaEm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EquipamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HabilidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("ModT20");
                });

            modelBuilder.Entity("backend.Models.PericiaT20", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FichaT20Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaT20Id");

                    b.ToTable("PericiaT20");
                });

            modelBuilder.Entity("backend.Models.EquipamentoT20", b =>
                {
                    b.HasOne("backend.Models.FichaT20", "FichaT20")
                        .WithMany("Equipamentos")
                        .HasForeignKey("FichaT20Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaT20");
                });

            modelBuilder.Entity("backend.Models.HabilidadeT20", b =>
                {
                    b.HasOne("backend.Models.FichaT20", "Ficha")
                        .WithMany("Habilidades")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("backend.Models.ModT20", b =>
                {
                    b.HasOne("backend.Models.EquipamentoT20", "Equipamento")
                        .WithMany("Mods")
                        .HasForeignKey("EquipamentoId");

                    b.HasOne("backend.Models.HabilidadeT20", "Habilidade")
                        .WithMany("Mods")
                        .HasForeignKey("HabilidadeId");

                    b.Navigation("Equipamento");

                    b.Navigation("Habilidade");
                });

            modelBuilder.Entity("backend.Models.PericiaT20", b =>
                {
                    b.HasOne("backend.Models.FichaT20", "FichaT20")
                        .WithMany("Pericias")
                        .HasForeignKey("FichaT20Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaT20");
                });

            modelBuilder.Entity("backend.Models.EquipamentoT20", b =>
                {
                    b.Navigation("Mods");
                });

            modelBuilder.Entity("backend.Models.FichaT20", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Habilidades");

                    b.Navigation("Pericias");
                });

            modelBuilder.Entity("backend.Models.HabilidadeT20", b =>
                {
                    b.Navigation("Mods");
                });
#pragma warning restore 612, 618
        }
    }
}
